### ISSUE TITLE
why is there c++ everywhere?

### ISSUE THREAD

**Issue by SpeXalys** [thevalencyproject/valency-core#4]
there is so much c++!! 
CODE IN PYTHON >:(

**Comment by isaacljubic** [comment]
Thank you for taking the time to check out the repository and for your feedback. I understand your concern regarding the extensive use of C++ in this project. The decision to use C++ was made primarily for its efficiency and advanced memory management capabilities, which are crucial for the performance and scalability of the frameworks in this repository.

While Python is indeed a very powerful and versatile language with a more straightforward syntax, for the specific needs of this project, C++ offers the necessary control and optimization. However, I appreciate your perspective and am open to discussing how we can make the codebase more accessible or integrate Python where possible for easier understanding and collaboration.

If you have specific suggestions or areas where you believe Python could be utilized without compromising performance, I would love to hear them! Your contributions or ideas on how to improve the code or documentation are most welcome.

IM GONNA CODE IN C++ >:(

**Comment by SpeXalys** [comment]
🤓🤓

**Comment by isaacljubic** [comment]
> 🤓🤓
![maxresdefault](https://github.com/thevalencyproject/valency-core/assets/134184959/3c6cfce5-eede-4990-93f0-9722b8f04c4a)
